name: dart_chat_webdev
description: Chat for Dart - Webdev part.
version: 0.1.0
author: Stéphane Este-Gracias <sestegra@gmail.com>
publish_to: none

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  angular: ^4.0.0-beta
  angular_components: 0.6.0-beta
  angular_forms: ^0.1.0
  browser: ^0.10.0+2
  dart_chat_common:
    path: ../dart_chat_common
  dart_to_js_script_rewriter: ^1.0.3

dev_dependencies:
  dart_sass_transformer: 0.5.0+1
  sass_builder: ^0.2.0+1
  test: ^0.12.0

transformers:
- angular:
    entry_points: web/index.dart
- angular/transform/reflection_remover:
    $include: test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter
- dart_sass_transformer

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
web:
  compiler:
    debug: dartdevc
